# version: "3.9"
# services:
#   python:
#     build: .
#     ports:
#       - "5901"
#     volumes:
#       - .:/usr/src/LAB
#   redis:
#     image: "mysql"
#     restart: always
#     command: --default-authentication-plugin=mysql_native_passwordk
#     environment:
#       MYSQL_ROOT_PASSWORD: user

version: '3'

services:
  vnc:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_DATABASE: new_schema
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    expose:
      # Opens port 3306 on the container
      - '3306'