# version: "3.9"
# services:
#   python:
#     build: .
#     ports:
#       - "5901"
#     volumes:
#       - .:/usr/src/LAB
#   redis:
#     image: "mysql"
#     restart: always
#     command: --default-authentication-plugin=mysql_native_passwordk
#     environment:
#       MYSQL_ROOT_PASSWORD: user

version: '3'

services:
  vnc:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080